name: Probe

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-liberation
          sudo apt-get install -y python3-pip
          sudo pip3 install art

      - name: Run Probe
        run: |
          wget https://raw.githubusercontent.com/whoami-anoint/Probe/main/make.py
          python3 make.py
